name: Container Images

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build container image
        run: |
          DOCKER_BUILDKIT=1 docker build -t aws-ebs-csi-driver . --target amazonlinux
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.GH_ACTIONS_AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.GH_ACTIONS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
          role-duration-seconds: 1200
          role-session-name: GitHubActions
          aws-region: us-east-1
      - name: log-in to ECR
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 204717343847.dkr.ecr.us-east-1.amazonaws.com
      - name: Push to ECR repo
        run: |
          TAG=$(git describe --always --abbrev=8)
          IMG=204717343847.dkr.ecr.us-east-1.amazonaws.com/infura-dedicated/aws-ebs-csi-driver:$TAG
          docker tag aws-ebs-csi-driver $IMG
          docker push $IMG
